package com.anvipo.angram.presentationLayer.flows.authFlow.coordinator.screensFactory.authorizationScreensFactory

import com.anvipo.angram.presentationLayer.flows.authFlow.coordinator.screensFactory.addProxyScreenFactory.AddProxyScreenFactory
import com.anvipo.angram.presentationLayer.flows.authFlow.coordinator.screensFactory.enterAuthCodeScreenFactory.EnterAuthenticationCodeScreenFactory
import com.anvipo.angram.presentationLayer.flows.authFlow.coordinator.screensFactory.enterPasswordScreenFactory.EnterAuthenticationPasswordScreenFactory
import com.anvipo.angram.presentationLayer.flows.authFlow.coordinator.screensFactory.enterPhoneNumberScreenFactory.EnterPhoneNumberScreenFactory

class AuthorizationScreensFactoryImp(
    override val enterPhoneNumberScreenFactory: EnterPhoneNumberScreenFactory,
    override val enterAuthenticationCodeScreenFactory: EnterAuthenticationCodeScreenFactory,
    override val enterAuthenticationPasswordScreenFactory: EnterAuthenticationPasswordScreenFactory,
    override val addProxyScreenFactory: AddProxyScreenFactory
) : AuthorizationScreensFactory
