package com.anvipo.angram.presentationLayer.userStories.mainUserStory.coordinator.interfaces

import com.anvipo.angram.presentationLayer.common.interfaces.BaseRouteEventHandler

interface MainCoordinatorRouteEventHandler : BaseRouteEventHandler