package com.anvipo.angram.applicationLayer.coordinator.interfaces

import com.anvipo.angram.presentationLayer.common.interfaces.BaseRouteEventHandler

interface ApplicationCoordinatorRouteEventHandler : BaseRouteEventHandler
