package com.anvipo.angram.layers.presentation.flows.authorization.coordinator.screensFactory.enterAuthenticationPhoneNumber

import com.anvipo.angram.layers.presentation.flows.authorization.screens.enterAuthenticationPhoneNumber.view.navigation.EnterAuthenticationPhoneNumberScreen

interface EnterAuthenticationPhoneNumberScreenFactory {

    fun createEnterAuthenticationPhoneNumberScreen(): EnterAuthenticationPhoneNumberScreen

}