package com.anvipo.angram.presentationLayer.userStories.authUserStory.coordinator.screensFactory.authorizationScreensFactory

import com.anvipo.angram.presentationLayer.userStories.authUserStory.coordinator.screensFactory.enterAuthCodeScreenFactory.EnterAuthenticationCodeScreenFactory
import com.anvipo.angram.presentationLayer.userStories.authUserStory.coordinator.screensFactory.enterPasswordScreenFactory.EnterPasswordScreenFactory
import com.anvipo.angram.presentationLayer.userStories.authUserStory.coordinator.screensFactory.enterPhoneNumberScreenFactory.EnterPhoneNumberScreenFactory

interface AuthorizationScreensFactory {

    val enterPhoneNumberScreenFactory: EnterPhoneNumberScreenFactory

    val enterAuthenticationCodeScreenFactory: EnterAuthenticationCodeScreenFactory

    val enterPasswordScreenFactory: EnterPasswordScreenFactory

}