package com.anvipo.angram.presentationLayer.flows.auth.coordinator.screensFactory.authorization

import com.anvipo.angram.presentationLayer.flows.auth.coordinator.screensFactory.addProxy.AddProxyScreenFactory
import com.anvipo.angram.presentationLayer.flows.auth.coordinator.screensFactory.enterAuthenticationCode.EnterAuthenticationCodeScreenFactory
import com.anvipo.angram.presentationLayer.flows.auth.coordinator.screensFactory.enterAuthenticationPassword.EnterAuthenticationPasswordScreenFactory
import com.anvipo.angram.presentationLayer.flows.auth.coordinator.screensFactory.enterPhoneNumber.EnterPhoneNumberScreenFactory

class AuthorizationScreensFactoryImp(
    override val enterPhoneNumberScreenFactory: EnterPhoneNumberScreenFactory,
    override val enterAuthenticationCodeScreenFactory: EnterAuthenticationCodeScreenFactory,
    override val enterAuthenticationPasswordScreenFactory: EnterAuthenticationPasswordScreenFactory,
    override val addProxyScreenFactory: AddProxyScreenFactory
) : AuthorizationScreensFactory
